###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = alacritty
$terminal2 = kitty
$fileManager = nautilus
$menu = rofi -show drun
$browser = chromium
