# Hyprland Theme — Gruvbox (Light)
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(b57614ff) rgba(af3a03ff) 45deg
    col.inactive_border = rgba(d5c4a1aa)
    resize_on_border = true
}
decoration {
    rounding = 10
    shadow {
        enabled = true
        range = 20
        render_power = 3
        color = rgba(d5c4a1aa)
    }
    blur {
        enabled = true
        size = 6
        passes = 3
        ignore_opacity = true
        new_optimizations = true
    }
}
blurls = rofi
blurls = wlogout
