# Light Theme Configuration
# Catppuccin Latte Blue Theme

general {
    # Active border gradient
     col.active_border   = rgba(7287fdff) rgba(04a5e5ff) 45deg

    # Soft inactive border
    col.inactive_border = rgba(bac2deaa)
}

decoration {
    shadow {
        # Soft light-mode shadow
        color = rgba(cdd6f4aa)
    }
}

# Blur effects
blurls = wlogout
blurls = rofi




























