# Kitty Theme — Everforest (Dark)
foreground            #d3c6aa
background            #2d353b
selection_foreground  #d3c6aa
selection_background  #543a48
cursor                #d3c6aa
cursor_text_color     #2d353b
url_color             #7fbbb3

color0   #475258
color1   #e67e80
color2   #a7c080
color3   #dbbc7f
color4   #7fbbb3
color5   #d699b6
color6   #83c092
color7   #d3c6aa
color8   #475258
color9   #e67e80
color10  #a7c080
color11  #dbbc7f
color12  #7fbbb3
color13  #d699b6
color14  #83c092
color15  #d3c6aa

active_border_color   #a7c080
inactive_border_color #374145
bell_border_color     #e67e80
active_tab_background #a7c080
active_tab_foreground #2d353b
inactive_tab_background #343f44
inactive_tab_foreground #859289
